extends RefCounted

# POC-26B: Shared Shot Decision Contract
# --------------------------------------
# Separates WHAT/HOW is chosen from authoritative shot execution. The contract
# exposes a bounded list of candidate indexes to a decision source, while keeping
# the full execution dictionaries private to the simulation. A human therefore
# selects an intent, never supplies an outcome or arbitrary physics payload.
#
# AI and human choices both execute through the existing DataDefinedAutonomousHole
# / AutonomousHole / putting models. The special AI putting candidate preserves
# the exact continuous strategy generated by POC-15; human-selectable putting
# candidates expose the same established pace range as LAG / NEUTRAL / ATTACK.

const PUTT := 3
const FEET_PER_YARD := 3.0
const HUMAN := "HUMAN"
const AI := "AI"
const POSITION_EPSILON := 0.001

var _decision_serial: int = 0
var _pending_playable = null
var _pending_golfer: Node = null
var _pending_state = null
var _pending_candidates: Array = []
var _pending_kind: String = ""
var _pending_decision_id: String = ""
var _pending_strokes: int = -1
var _pending_position: Vector3 = Vector3.ZERO
var _pending_ai_index: int = -1
var _pending_strategy_evaluated: Array = []


func has_pending_decision() -> bool:
	return _pending_playable != null and _pending_golfer != null and _pending_state != null and not _pending_candidates.is_empty()


func prepare(playable, golfer: Node, state) -> Dictionary:
	if has_pending_decision() or playable == null or golfer == null or state == null:
		return {}
	if not state.can_continue():
		return {}

	_pending_playable = playable
	_pending_golfer = golfer
	_pending_state = state
	_pending_candidates.clear()
	_pending_strategy_evaluated.clear()
	_pending_ai_index = -1
	_pending_strokes = int(state.strokes)
	_pending_position = state.ball_position
	_decision_serial += 1
	var hole_number: int = int(playable.hole_definition.hole_number) if playable.hole_definition != null else 0
	_pending_decision_id = "H%d-S%d-D%d" % [hole_number, _pending_strokes + 1, _decision_serial]

	var surface: String = state.surface_name()
	if surface == "GREEN":
		if not _build_putting_candidates():
			_clear_pending()
			return {}
	elif state.remaining_distance() <= 8.0:
		if not _build_legacy_candidates("SHORT_GAME"):
			_clear_pending()
			return {}
	else:
		var selection: Dictionary = playable.choose_course_strategy(golfer, state)
		var evaluated: Array = selection.get("evaluated", [])
		if evaluated.is_empty():
			if not _build_legacy_candidates("LEGACY_FALLBACK"):
				_clear_pending()
				return {}
		else:
			_build_course_strategy_candidates(evaluated)

	if _pending_candidates.is_empty():
		_clear_pending()
		return {}
	return decision_package()


func decision_package() -> Dictionary:
	if not has_pending_decision():
		return {}
	var choices: Array = []
	for index in range(_pending_candidates.size()):
		choices.append(_choice_summary(index, _pending_candidates[index]))
	return {
		"decision_id": _pending_decision_id,
		"decision_kind": _pending_kind,
		"situation": _situation_snapshot(),
		"choices": choices,
		"choice_count": choices.size()
	}


func choose_ai_candidate() -> int:
	if not has_pending_decision() or not _pending_is_current():
		return -1
	if _pending_ai_index >= 0 and _pending_ai_index < _pending_candidates.size():
		return _pending_ai_index

	# Legacy short-game options retain the exact golfer behavioral decision path.
	var options: Array = []
	for candidate in _pending_candidates:
		options.append(candidate.get("option", {}).duplicate(true))
	if options.is_empty():
		return -1
	var chosen: Dictionary = _pending_golfer.choose_best_option(options)
	for index in range(options.size()):
		if options[index] == chosen:
			_pending_ai_index = index
			return index
	return -1


func execute_candidate(candidate_index: int, choice_source: String = HUMAN) -> Dictionary:
	if not has_pending_decision():
		return {"executed": false, "reason": "NO_PENDING_DECISION"}
	if not _pending_is_current():
		var stale_id: String = _pending_decision_id
		_clear_pending()
		return {"executed": false, "reason": "STALE_DECISION", "decision_id": stale_id}
	if candidate_index < 0 or candidate_index >= _pending_candidates.size():
		return {"executed": false, "reason": "INVALID_CANDIDATE_INDEX", "decision_id": _pending_decision_id}

	var source: String = choice_source.to_upper()
	if source != HUMAN and source != AI:
		return {"executed": false, "reason": "INVALID_CHOICE_SOURCE", "decision_id": _pending_decision_id}
	var candidate: Dictionary = _pending_candidates[candidate_index]
	if source == HUMAN and not bool(candidate.get("human_selectable", true)):
		return {"executed": false, "reason": "CANDIDATE_NOT_HUMAN_SELECTABLE", "decision_id": _pending_decision_id}

	var decision_id: String = _pending_decision_id
	var kind: String = _pending_kind
	var shot: Dictionary = {}
	var mode: String = str(candidate.get("mode", ""))
	if mode == "COURSE_STRATEGY":
		var chosen: Dictionary = candidate.get("choice", {}).duplicate(true)
		shot = _pending_playable._execute_course_strategy_choice(
			_pending_golfer,
			_pending_state,
			chosen,
			_pending_strategy_evaluated
		)
	elif mode == "PUTTING":
		shot = _execute_legacy_choice(
			candidate.get("option", {}).duplicate(true),
			candidate.get("putting_strategy", {}).duplicate(true),
			candidate.get("putting_read", {}).duplicate(true)
		)
	elif mode == "LEGACY":
		shot = _execute_legacy_choice(candidate.get("option", {}).duplicate(true))

	if shot.is_empty():
		return {"executed": false, "reason": "AUTHORITATIVE_EXECUTION_FAILED", "decision_id": decision_id}

	shot["decision_id"] = decision_id
	shot["decision_kind"] = kind
	shot["decision_candidate_index"] = candidate_index
	shot["choice_source"] = source
	shot["decision_choice"] = _choice_summary(candidate_index, candidate)
	# Course-strategy execution records history before returning; overwrite the
	# latest history item so decision provenance is preserved there as well.
	if _pending_playable.autonomous != null and not _pending_playable.autonomous.shot_history.is_empty():
		_pending_playable.autonomous.shot_history[-1] = shot.duplicate(true)

	var state_after: Dictionary = _pending_state.snapshot()
	var hole_ended: bool = not _pending_state.can_continue()
	_clear_pending()
	return {
		"executed": true,
		"decision_id": decision_id,
		"decision_kind": kind,
		"candidate_index": candidate_index,
		"choice_source": source,
		"shot": shot.duplicate(true),
		"state_after": state_after,
		"hole_ended": hole_ended
	}


func cancel_pending_decision() -> void:
	_clear_pending()


func _build_course_strategy_candidates(evaluated: Array) -> void:
	_pending_kind = "COURSE_STRATEGY"
	_pending_strategy_evaluated = evaluated.duplicate(true)
	for base_index in range(evaluated.size()):
		var base: Dictionary = evaluated[base_index].duplicate(true)
		var intents: Array = base.get("evaluated_intents", [])
		if intents.is_empty():
			_pending_candidates.append({
				"mode": "COURSE_STRATEGY",
				"human_selectable": true,
				"choice": base,
				"base_candidate_index": base_index,
				"intent_index": 0
			})
			continue
		for intent_index in range(intents.size()):
			var intent_evaluation: Dictionary = intents[intent_index]
			var choice: Dictionary = base.duplicate(true)
			choice["chosen_intent"] = intent_evaluation.get("intent", {}).duplicate(true)
			choice["chosen_predicted_flight"] = intent_evaluation.get("predicted_flight", {}).duplicate(true)
			choice["chosen_proficiency"] = intent_evaluation.get("proficiency", {}).duplicate(true)
			choice["intent_decision_cost"] = float(intent_evaluation.get("intent_decision_cost", INF))
			_pending_candidates.append({
				"mode": "COURSE_STRATEGY",
				"human_selectable": true,
				"choice": choice,
				"base_candidate_index": base_index,
				"intent_index": intent_index
			})
	# CourseStrategySelector sorts both club/target candidates and their intent
	# evaluations best-first. Flattened candidate zero is therefore the exact
	# autonomous recommendation that existed before the contract.
	_pending_ai_index = 0 if not _pending_candidates.is_empty() else -1


func _build_legacy_candidates(kind: String) -> bool:
	var hazards: Array = _pending_playable._legacy_water_hazards()
	var generated: Array = _pending_playable.autonomous.option_generator.generate_options(_pending_golfer, _pending_state, hazards)
	if generated.is_empty():
		return false
	var options: Array = _pending_playable.autonomous.assessment_pipeline.assess_options(
		_pending_golfer,
		_pending_state,
		generated,
		hazards
	)
	if options.is_empty():
		return false
	_pending_kind = kind
	for option in options:
		_pending_candidates.append({
			"mode": "LEGACY",
			"human_selectable": true,
			"option": option.duplicate(true)
		})
	return true


func _build_putting_candidates() -> bool:
	var hazards: Array = _pending_playable._legacy_water_hazards()
	var generated: Array = _pending_playable.autonomous.option_generator.generate_options(_pending_golfer, _pending_state, hazards)
	if generated.is_empty():
		return false
	var options: Array = _pending_playable.autonomous.assessment_pipeline.assess_options(
		_pending_golfer,
		_pending_state,
		generated,
		hazards
	)
	var putt_option: Dictionary = {}
	for option in options:
		if int(option.get("shot_type", -1)) == PUTT:
			putt_option = option.duplicate(true)
			break
	if putt_option.is_empty():
		return false

	var start: Vector3 = _pending_state.ball_position
	var distance_feet: float = start.distance_to(_pending_state.hole_position) * FEET_PER_YARD
	var slope_across: float = float(putt_option.get("slope_across_percent", 0.0))
	var slope_along: float = float(putt_option.get("slope_along_percent", 0.0))
	var green_speed: float = float(putt_option.get("green_speed", 10.0))
	var pipeline = _pending_playable.autonomous.putting_pipeline
	var read: Dictionary = pipeline.read_model.plan_putt(distance_feet, slope_across, slope_along, green_speed)
	var ai_strategy: Dictionary = pipeline.strategy_model.choose_strategy(_pending_golfer, read)

	_pending_kind = "PUTTING"
	# Candidate zero exactly preserves the existing autonomous continuous strategy.
	_pending_candidates.append({
		"mode": "PUTTING",
		"human_selectable": false,
		"option": putt_option.duplicate(true),
		"putting_read": read.duplicate(true),
		"putting_strategy": ai_strategy.duplicate(true),
		"putting_choice_label": "AI_PROFILE"
	})
	_pending_ai_index = 0

	# Human pace choices use the pace range already established in POC-15D:
	# -0.30 ft to +0.35 ft around the base read, with the same capture safeguard.
	for pace_choice in [
		{"label": "LAG", "adjustment": -0.30},
		{"label": "NEUTRAL", "adjustment": 0.0},
		{"label": "ATTACK", "adjustment": 0.35}
	]:
		var strategy: Dictionary = _putting_strategy_variant(
			ai_strategy,
			str(pace_choice["label"]),
			float(pace_choice["adjustment"])
		)
		_pending_candidates.append({
			"mode": "PUTTING",
			"human_selectable": true,
			"option": putt_option.duplicate(true),
			"putting_read": read.duplicate(true),
			"putting_strategy": strategy,
			"putting_choice_label": str(pace_choice["label"])
		})
	return true


func _putting_strategy_variant(ai_strategy: Dictionary, label: String, pace_adjustment_feet: float) -> Dictionary:
	var result: Dictionary = ai_strategy.duplicate(true)
	var distance_feet: float = maxf(0.0, float(result.get("distance_feet", 0.0)))
	var base_intended: float = maxf(0.0, float(result.get("base_intended_distance_feet", result.get("intended_distance_feet", distance_feet))))
	var intended: float = maxf(distance_feet - 0.15, base_intended + pace_adjustment_feet)
	result["strategy"] = label
	result["strategy_pace_adjustment_feet"] = pace_adjustment_feet
	result["intended_distance_feet"] = intended
	result["pace_feet_past_hole"] = maxf(0.0, intended - distance_feet)
	return result


func _execute_legacy_choice(chosen: Dictionary, explicit_putting_strategy: Dictionary = {}, putting_read: Dictionary = {}) -> Dictionary:
	if chosen.is_empty():
		return {}
	var autonomous = _pending_playable.autonomous
	var state = _pending_state
	var golfer = _pending_golfer
	var surface_before: String = state.surface_name()
	var lie_quality_before: float = state.current_lie_quality
	var hazards: Array = _pending_playable._legacy_water_hazards()
	var options: Array = []
	for candidate in _pending_candidates:
		var option: Dictionary = candidate.get("option", {})
		if not option.is_empty() and not options.has(option):
			options.append(option.duplicate(true))
	if options.is_empty():
		options.append(chosen.duplicate(true))

	var decision_assessment: Dictionary = autonomous.decision_evaluator.evaluate(golfer, chosen, options)
	var commitment: Dictionary = autonomous.assessment_pipeline.prepare_execution(
		golfer,
		chosen,
		float(decision_assessment["gap"])
	)
	var result: Dictionary
	if int(chosen.get("shot_type", -1)) == PUTT and not explicit_putting_strategy.is_empty():
		result = _execute_selected_putt(chosen, explicit_putting_strategy, putting_read)
	else:
		result = autonomous._execute_option(golfer, state, chosen, hazards, commitment)

	result["selected_option"] = chosen.duplicate(true)
	result["surface_before"] = surface_before
	result["lie_quality_before"] = lie_quality_before
	result["decision_quality"] = decision_assessment["quality"]
	result["decision_score"] = decision_assessment["score"]
	result["decision_best_score"] = decision_assessment["best_score"]
	result["decision_gap"] = decision_assessment["gap"]
	result["decision_best_option"] = decision_assessment["best_option"]
	result["decision_reason"] = decision_assessment["reason"]
	result["decision_chosen_breakdown"] = decision_assessment.get("chosen_breakdown", {}).duplicate(true)
	result["decision_best_breakdown"] = decision_assessment.get("best_breakdown", {}).duplicate(true)
	result["decision_option_breakdowns"] = decision_assessment.get("option_breakdowns", []).duplicate(true)
	result["commitment_score"] = commitment["score"]
	result["commitment_quality"] = commitment["label"]
	result["assessment"] = chosen.get("assessment", {}).duplicate(true)

	if state.course_context != null and int(result["shot_type"]) != PUTT:
		var landing_surface = state.course_context.surface_at(result["landing_position"])
		if state.course_context.surface_name(landing_surface) == "WATER":
			result["outcome"] = "WATER"
			result["penalty_strokes"] = max(int(result["penalty_strokes"]), 1)

	var next_position: Vector3 = result["landing_position"]
	if result["outcome"] == "WATER":
		var entry_point = autonomous._find_water_entry_point(state, result["start_position"], result["landing_position"])
		next_position = autonomous._lateral_water_relief_position(state, entry_point, result["start_position"])
		result["water_entry_point"] = entry_point
		result["relief_position"] = next_position
	else:
		result["water_entry_point"] = result["landing_position"]
		result["relief_position"] = result["landing_position"]
	var hole_radius: float = 0.01 if int(result["shot_type"]) == PUTT else 2.0
	state.advance_to(next_position, result["outcome"], result["penalty_strokes"], hole_radius)
	result["surface_after"] = state.surface_name()
	result["lie_quality_after"] = state.current_lie_quality
	var execution_assessment: Dictionary = autonomous._assess_execution(result)
	result["execution_quality"] = execution_assessment["quality"]
	result["execution_score"] = execution_assessment["score"]
	result["execution_miss_distance"] = execution_assessment["miss_distance"]
	result["execution_reason"] = execution_assessment["reason"]
	autonomous.assessment_pipeline.record_result(chosen, result)
	autonomous.shot_history.append(result)
	golfer.record_shot_result(result["outcome"], bool(chosen.get("is_aggressive", false)))
	return result


func _execute_selected_putt(option: Dictionary, strategy: Dictionary, read: Dictionary) -> Dictionary:
	var state = _pending_state
	var golfer = _pending_golfer
	var pipeline = _pending_playable.autonomous.putting_pipeline
	var start: Vector3 = state.ball_position
	var target: Vector3 = state.hole_position
	var direction: Vector3 = target - start
	direction.y = 0.0
	var distance_yards: float = direction.length()
	if distance_yards <= 0.0001:
		direction = Vector3.FORWARD
	else:
		direction = direction.normalized()
	var lateral: Vector3 = Vector3(-direction.z, 0.0, direction.x)
	var proficiency: Dictionary = pipeline.proficiency_model.assess(golfer, strategy)
	var execution: Dictionary = pipeline.execution_model.realize(strategy, proficiency, int(randi()))
	var roll: Dictionary = pipeline.roll_model.resolve(strategy, execution)
	var holed: bool = bool(roll.get("holed", false))
	var rolled_yards: float = float(roll.get("rolled_distance_feet", 0.0)) / FEET_PER_YARD
	var lateral_yards: float = float(roll.get("final_lateral_feet", 0.0)) / FEET_PER_YARD
	var landing: Vector3
	if holed:
		landing = target
	else:
		landing = start + direction * rolled_yards + lateral * lateral_yards
		landing.y = start.y
	var putting := {
		"read": read.duplicate(true),
		"strategy": strategy.duplicate(true),
		"proficiency": proficiency.duplicate(true),
		"execution": execution.duplicate(true),
		"roll": roll.duplicate(true),
		"holed": holed,
		"finish_distance_from_hole_feet": float(roll.get("finish_distance_from_hole_feet", 0.0)),
		"final_lateral_feet": float(roll.get("final_lateral_feet", 0.0)),
		"rolled_distance_feet": float(roll.get("rolled_distance_feet", 0.0))
	}
	return {
		"shot_number": state.strokes + 1,
		"option": option.get("name", "PUTT"),
		"shot_type": PUTT,
		"club_id": option.get("club_id", "PUTTER"),
		"club_name": option.get("club_name", "Putter"),
		"club_effective_carry": distance_yards,
		"club_dispersion": 0.25,
		"start_position": start,
		"target_position": target,
		"landing_position": landing,
		"intended_distance": distance_yards,
		"outcome": "HOLED" if holed else "SUCCESS",
		"penalty_strokes": 0,
		"execution_roll": -1.0,
		"remaining_after_shot": landing.distance_to(target),
		"lateral_error": lateral_yards,
		"distance_error": rolled_yards - distance_yards,
		"putting": putting,
		"putting_strategy": str(strategy.get("strategy", "NEUTRAL")),
		"putting_holed": holed,
		"putting_finish_distance_feet": float(roll.get("finish_distance_from_hole_feet", 0.0))
	}


func _choice_summary(index: int, candidate: Dictionary) -> Dictionary:
	var mode: String = str(candidate.get("mode", ""))
	var choice: Dictionary = candidate.get("choice", {}) if mode == "COURSE_STRATEGY" else candidate.get("option", {})
	var summary := {
		"index": index,
		"human_selectable": bool(candidate.get("human_selectable", true)),
		"mode": mode,
		"name": str(choice.get("name", "")),
		"club_id": str(choice.get("club_id", "")),
		"club_name": str(choice.get("club_name", "")),
		"shot_type": int(choice.get("shot_type", -1)),
		"target_position": choice.get("target_position", choice.get("target", Vector3.ZERO)),
		"target_variant": str(choice.get("target_variant", "")),
		"strategy_posture": str(choice.get("strategy_posture", ""))
	}
	if mode == "COURSE_STRATEGY":
		summary["decision_expected_strokes"] = float(choice.get("decision_expected_strokes", INF))
		summary["intent"] = choice.get("chosen_intent", {}).duplicate(true)
		summary["predicted_flight"] = choice.get("chosen_predicted_flight", {}).duplicate(true)
	elif mode == "PUTTING":
		summary["putting_strategy"] = str(candidate.get("putting_choice_label", ""))
		summary["intended_distance_feet"] = float(candidate.get("putting_strategy", {}).get("intended_distance_feet", 0.0))
	return summary


func _situation_snapshot() -> Dictionary:
	if _pending_state == null:
		return {}
	return {
		"hole_number": int(_pending_playable.hole_definition.hole_number) if _pending_playable != null and _pending_playable.hole_definition != null else 0,
		"hole_name": str(_pending_playable.hole_definition.hole_name) if _pending_playable != null and _pending_playable.hole_definition != null else "",
		"shot_number": int(_pending_state.strokes) + 1,
		"ball_position": _pending_state.ball_position,
		"hole_position": _pending_state.hole_position,
		"remaining_distance_yards": _pending_state.remaining_distance(),
		"surface": _pending_state.surface_name(),
		"lie_quality": float(_pending_state.current_lie_quality)
	}


func _pending_is_current() -> bool:
	return (
		has_pending_decision()
		and _pending_state.can_continue()
		and int(_pending_state.strokes) == _pending_strokes
		and _pending_state.ball_position.distance_to(_pending_position) <= POSITION_EPSILON
	)


func _clear_pending() -> void:
	_pending_playable = null
	_pending_golfer = null
	_pending_state = null
	_pending_candidates.clear()
	_pending_kind = ""
	_pending_decision_id = ""
	_pending_strokes = -1
	_pending_position = Vector3.ZERO
	_pending_ai_index = -1
	_pending_strategy_evaluated.clear()
